name: Build Airsaned packages

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        wrtrel:
          - 24.10.2
          - 24.10.3
        sdk:
          - mediatek-filogic

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Build Airsaned package for OpenWRT
        uses: cmangla/gh-action-sdk@pr-hash-fixup-option
        env:
          ARCH: ${{ matrix.sdk }}-${{ matrix.wrtrel }}
          EXTRA_FEEDS: src-git|airsaned|${{ github.server_url }}/${{ github.repository }}.git^${{ github.sha }}
          PACKAGES: airsaned
          FIXUP: 1
          V: w # s=(stdout+stderr), w=warnings, c=commands

      - name: Obtain full package version
        run: bash ./.github/work.sh pkg-ver airsaned/Makefile | tee $GITHUB_ENV
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: airsaned_${{ env.PKG_FULL_VERSION }}_openwrt-${{ matrix.wrtrel }}_${{ matrix.sdk }}.ipk.d
          path: bin/packages/**/airsaned_*.ipk

